//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRooms
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime Day { get; set; }
        public string Type { get; set; }
        public int MaxClient { get; set; }
        public int StatusId { get; set; }
        public decimal Cost { get; set; }
        public Nullable<int> QuerryId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
