//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public int FlightNumber { get; set; }
        public System.DateTime Departure { get; set; }
        public System.DateTime Landing { get; set; }
        public string StartCountry { get; set; }
        public string StartCity { get; set; }
        public string EndCountry { get; set; }
        public string EndCity { get; set; }
        public int StatusId { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Companies Companies { get; set; }
        public virtual Requests Requests { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
